version: '3'

services:
  physicalflows_data:
    container_name: physicalflows_data
    restart: always
    build:
      context: ./data
      dockerfile: Dockerfile
    #image: physicalflows_data
    ports:
      - "9001:9001"

  physicalflows_applogic:
    container_name: physicalflows_applogic
    restart: always
    build:
      context: ./app_logic
      dockerfile: Dockerfile
    #image: physicalflows_applogic
    ports:
      - "9051:9051"

  userservice:
    container_name: userservice
    restart: always
    build:
      context: ../../user-service
      dockerfile: Dockerfile
    #image: userservice
    ports:
      - "5000:5000"
      
  mongodb:
    container_name: mongodb
    image: mongo
    ports: 
      - "27017:27017" 
    volumes:
      - "data-vol:/data/db"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    hostname: rabbitmqhost
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  data-vol:
